// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    'intro', // Modules overview page
    {
      type: 'category',
      label: 'ROS 2 Module',
      items: [
        'ros2-module/001',
        'ros2-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Fundamentals',
          items: ['ros2-module/chapter-1/fundamentals'],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Communication Model',
          items: ['ros2-module/chapter-2/communication-model'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Python AI Agents with ROS 2',
          items: ['ros2-module/chapter-3/ai-agents'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Humanoid Modeling with URDF',
          items: ['ros2-module/chapter-4/urdf-modeling'],
        },
        {
          type: 'category',
          label: 'Integration Project',
          items: ['ros2-module/integration-project/integration'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 02: Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: Digital Twins in Physical AI',
          items: ['digital-twin-module/chapter-1/digital-twin-fundamentals'],
        },
        {
          type: 'category',
          label: 'Chapter 2: Physics Simulation with Gazebo',
          items: ['digital-twin-module/chapter-2/gazebo-physics-simulation'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Interaction & Visualization with Unity',
          items: ['digital-twin-module/chapter-3/unity-visualization'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Simulated Sensors',
          items: ['digital-twin-module/chapter-4/simulated-sensors'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 03: Isaac (NVIDIA AI-Robot Brain)',
      items: [
        'isaac-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: NVIDIA Isaac Ecosystem',
          items: ['isaac-module/chapter-1/isaac-ecosystem'],
        },
        {
          type: 'category',
          label: 'Chapter 2: Isaac Sim & Synthetic Data',
          items: ['isaac-module/chapter-2/synthetic-data'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Isaac ROS & Visual SLAM',
          items: ['isaac-module/chapter-3/visual-slam'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Nav2 Navigation for Humanoids',
          items: ['isaac-module/chapter-4/navigation'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Build & Deployment Module',
      items: [
        'build-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: Containerization & Docker',
          items: ['build-module/chapter-1/containerization'],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Build Systems',
          items: ['build-module/chapter-2/build-systems'],
        },
        {
          type: 'category',
          label: 'Chapter 3: CI/CD Pipelines',
          items: ['build-module/chapter-3/cicd-pipelines'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Cloud Deployment & Monitoring',
          items: ['build-module/chapter-4/cloud-deployment'],
        },
        {
          type: 'category',
          label: 'Integration Project: Complete Build & Deployment System',
          items: ['build-module/integration-project/integration'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus Module',
      items: [
        'docusaurus-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: Docusaurus Fundamentals',
          items: ['docusaurus-module/chapter-1/fundamentals'],
        },
        {
          type: 'category',
          label: 'Chapter 2: Project Structure & Routing',
          items: ['docusaurus-module/chapter-2/project-structure'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Writing Modules & Chapters in .md',
          items: ['docusaurus-module/chapter-3/writing-modules'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Theming, Search, and Plugins',
          items: ['docusaurus-module/chapter-4/theming-search-plugins'],
        },
        {
          type: 'category',
          label: 'Chapter 5: Build & Deployment to GitHub Pages',
          items: ['docusaurus-module/chapter-5/build-deployment'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Isaac Module',
      items: [
        'isaac-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: NVIDIA Isaac for Physical AI',
          items: ['isaac-module/chapter-1/isaac-ecosystem'],
        },
        {
          type: 'category',
          label: 'Chapter 2: Isaac Sim & Synthetic Data',
          items: ['isaac-module/chapter-2/synthetic-data'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Isaac ROS & Visual SLAM',
          items: ['isaac-module/chapter-3/visual-slam'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Navigation with Nav2 for Humanoids',
          items: ['isaac-module/chapter-4/navigation'],
        },
        {
          type: 'category',
          label: 'Integration Project: Complete Isaac AI System',
          items: ['isaac-module/integration-project/integration'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) Module',
      items: [
        'vla-module/intro',
        {
          type: 'category',
          label: 'Chapter 1: Vision-Language-Action Systems',
          items: ['vla-module/chapter-1/vla-systems'],
        },
        {
          type: 'category',
          label: 'Chapter 2: Voice-to-Action Interfaces',
          items: ['vla-module/chapter-2/voice-to-action'],
        },
        {
          type: 'category',
          label: 'Chapter 3: Language-Driven Cognitive Planning',
          items: ['vla-module/chapter-3/language-planning'],
        },
        {
          type: 'category',
          label: 'Chapter 4: Capstone — The Autonomous Humanoid',
          items: ['vla-module/chapter-4/capstone-autonomous-humanoid'],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
